### ISSUE TITLE
Project planner homes Z axis at end of print causing potential damage to printer

### ISSUE THREAD

**Issue by Onaka** [daid/LegacyCura#220]
When using project planner to simultaneously print several objects, once the print is done, the project planner drives the print head into one of the objects and then tries to home both the X and Y axes.
Kind of undesirable.

**Comment by daid** [comment]
There is a bug in the "all at once" mode, I fixed it a few days ago:
https://github.com/daid/Cura/commit/b1a7647c6e3ff1f3c52a0cd84d966acc48ab376a

And yes, it's very undesirable!

**Comment by mfeherpataky** [comment]
Oh yeah, this one. Glad you reported it @Onaka. It ruined my arcol hotend yesterday. It was the only time I used Cura, abandoned the whole thing afterwards and did not take time to investigate where it went wrong. 
Waiting for next release then.

**Comment by daid** [comment]
REALY sorry for you acrol hotend :'( :'(

I've worked out some more protection against this bug. And I'm working towards a release really fast now.

**Comment by mfeherpataky** [comment]
No worries, I was lucky enough to have one spare stainless steel barrel I bought from Laszlo so I was up again in no time. I also learned to review the end of the gcode now.

I really like Cura for slicing speed and quality and Joris is a great addition. Looking forward for next releases.

**Comment by rodrigopw** [comment]
Still having this problem...when can we expect a solution? Is the new fixed release coming soon? Is there a way to fix it? I sold a machine to a costumer that is always doing this multiprint job....i need to fix this asap...or the machine will be returned....slic3r crash with multiprint...cura is much better....but crashes the bed....please give me a hand to make this costumer keep the machine...
Best regards...rodrigo

**Comment by daid** [comment]
Should be fixed in the 12.11 release.

**Comment by daid** [comment]
Which can be found at: http://software.ultimaker.com/

**Comment by rodrigopw** [comment]
Thanks so much for you quick support!
Ill try in half an hour and let you know...
Best regards

Rodrigo
Enviado desde mi BlackBerry de Personal (http://www.personal.com.ar/)

-----Original Message-----
